theme: jekyll-theme-cayman
title: From Linux to K8s - Learn DevOps by Building
description: A curated, community-driven collection of free DevOps labs, challenges, and end-to-end projects — organized by category. Learn by doing, from Linux to Kubernetes.